version: '3.8'

services:
  app:
    build:
      context: .          # Sử dụng Dockerfile từ thư mục hiện tại
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "8000:8000"       # Expose ứng dụng trên port 8000
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: uicenter
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app    # Đồng bộ mã nguồn
      - /usr/src/app/node_modules
    command: sh -c "npm install && sleep 10 && npm run start:dev"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: uicenter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
