version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ui-center-be
    ports:
      - "8000:8000" # Expose NestJS app on port 8000
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres  # Service name of the PostgreSQL container (no change)
      DATABASE_PORT: 5433      # Internal port used by PostgreSQL container
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456  # Ensure the password matches the PostgreSQL settings
      DATABASE_NAME: uicenter
      DATABASE_SYNCHRONIZE: "true"
    depends_on:
      - postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    command: sh -c "npm install && npm run start:dev"

  postgres:
    image: postgres:15-alpine  # Use PostgreSQL version 13.7
    container_name: postgres
    ports:
      - "5433:5432"  # Map PostgreSQL container's port 5432 to host port 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456  # Ensure this matches the app service environment
      POSTGRES_DB: uicenter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
